#%RAML 1.0
types:
  bell:
    type: object
    description: Entity that show a bell of saxophone
    properties:
      id:
        type: string
        description: id unique for my bell
        required: false
      brand:
        type: string
        description: brand of my bell
        required: false
      model:
        type: string
        description: model of my bell
        required: false
      color:
        type: string
        description: color of my bell
        required: false
      material:
        type: string
        description: material on which the bell is built
        required: false
      price:
        type: number
        description: price of my bell
        required: false
    typeBell:
        type: string
        description: type of my bell
        required: false