#%RAML 1.0
types:
  keys:
    type: array
    description: Array of entities key
    items:
      properties:
        id:
          type: string
          description: id unique for my key
          required: false
        brand:
          type: string
          description: trademark of my key
          required: false
        price:
          type: number
          description: price of my key
          required: false
        quantity:
          type: number
          description: quantity of keys
          required: false
        saxophoneType:
          type: enum
          description: type of my saxophone
          required: false