#%RAML 1.0
title: instruments
version: v0
baseUri: http://instruments.com/{title}/{version}
types:
  neck:
    type: object
    description: Entity that show a neck for a saxophone
    properties:
      id:
        type: string
        description: id
        required: false
      brand:
        type: string
        description: brand
        required: false
      type:
        type: string
        description: type
        required: false
      model:
        type: string
        description: model
        required: false
      price:
        type: number
        description: price
        required: false
      material:
        type: string
        description: material
        required: false
/neck:
  get:
    responses:
      200:
        body:
          application/json:
            type: | 
              [
                {
                  "id": 1,
                  "brand": "Yamaha",
                  "model": "",
                  "color": "red",
                  "material": "wood",
                  "price": 1000,
                  "type": "Soprano" 
                }
              ]
            example: # example how a response looks like
              {
                "message": "OK",
                "data" : 
              }