#%RAML 1.0
types:
  saxophone:
    type: array
    description: Entity that show a saxophone
    properties:
      id:
        type: string
        description: id unique for my saxophone
        required: false
      trademark:
        type: string
        description: trademark of my saxophone
        required: false
      model:
        type: string
        description: model of my saxophone
        required: false
      color:
        type: string
        description: color of my saxophone
        required: false
      material:
        type: string
        description: material on which the saxophone is built
        required: false
      price:
        type: number
        description: price of my saxophone
        required: false
      saxophoneType:
        type: string
        description: type of my saxophone
        required: false